In [1]:
# Import libraries
import pandas as pd

In [2]:
# Load csv pre-processed CSV data as DataFrame
data = pd.read_csv("../data/output.csv")

df = pd.DataFrame(data)
df.head()

,Unnamed: 0,kepid,kepoi_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_impact,koi_duration,koi_depth,koi_prad,koi_teq,koi_model_snr,koi_steff,koi_slogg,koi_srad
0,0,10797460,K00752.01,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,0.146,2.95750,615.8,2.26,793.0,35.8,5455.0,4.467,0.927
1,1,10797460,K00752.02,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,0.586,4.50700,874.8,2.83,443.0,25.8,5455.0,4.467,0.927
2,2,10811496,K00753.01,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,19.899140,0.969,1.78220,10829.0,14.60,638.0,76.3,5853.0,4.544,0.868
3,3,10848459,K00754.01,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,1.276,2.40641,8079.2,33.46,1395.0,505.6,5805.0,4.564,0.791
4,4,10854555,K00755.01,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,0.701,1.65450,603.3,2.75,1406.0,40.9,6031.0,4.438,1.046

In [5]:
df = df.drop(columns=["Unnamed: 0"])
df.head()

,kepid,kepoi_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_impact,koi_duration,koi_depth,koi_prad,koi_teq,koi_model_snr,koi_steff,koi_slogg,koi_srad
0,10797460,K00752.01,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,0.146,2.95750,615.8,2.26,793.0,35.8,5455.0,4.467,0.927
1,10797460,K00752.02,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,0.586,4.50700,874.8,2.83,443.0,25.8,5455.0,4.467,0.927
2,10811496,K00753.01,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,19.899140,0.969,1.78220,10829.0,14.60,638.0,76.3,5853.0,4.544,0.868
3,10848459,K00754.01,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,1.276,2.40641,8079.2,33.46,1395.0,505.6,5805.0,4.564,0.791
4,10854555,K00755.01,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,0.701,1.65450,603.3,2.75,1406.0,40.9,6031.0,4.438,1.046